name: deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-lastest
    name: Build Proj
    steps:
      - uses: actions/checkout@v2
        name: checkout

      - name: Build web-app
        run: |
          npm ci
           npm run build
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3 

        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build  